name: Deploy tgl site in cpanel

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build the App
        run: npm run build
        env:
          CI: false
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          ftp-server: ftp.tgltechnology.com
          ftp-username: tgltechnology@tgltechnology.com
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
