name: Deploy tgl site in cpanel

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build the App
        run: npm run build
      - name: check contents
        run: |
          if [ -d "dist" ]; then
            echo "Folder exists"
            ls -la dist
          else 
            echo "Folder does not exist"
          fi
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.tgltechnology.com
          username: deploy@tgltechnology.com
          password: ${{ secrets.FTP_PASSWORD }}
          ftp_remote_dir: public_html
          protocol: ftps
          source_directory: ./dist/
